FORMAT: 1A
HOST: https://introsde-lifecoach-p-centric.herokuapp.com/

# IntroSDE - LifeCoah API

LifeCoah is a simple API allowing consumers to insert their meauseres and set some goals.

## User [/user/{+new|exist|profile|bmi}/{id}]

### New [POST]

create a person by specifying the chat id

+ Request (application/json)

        {
            
        }

+ Response 200 (application/json)

        [
            {
    
            }
        ]

### Exist [GET]
### Profile [GET]
### Bmi [GET]

## Measure [/measure]

### New [POST]
### Show [GET]

## Goal [/goal]
### New [POST]
### Show [GET]
### Delete [GET]


## Example [/example]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }