
package ws.storage;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StorageService", targetNamespace = "http://webservice.storage.lifecoach/", wsdlLocation = "https://introsde-lifecoach-storage.herokuapp.com/ws/storage/?wsdl")
public class StorageService
        extends Service {

    private final static URL STORAGESERVICE_WSDL_LOCATION;
    private final static WebServiceException STORAGESERVICE_EXCEPTION;
    private final static QName STORAGESERVICE_QNAME = new QName("http://webservice.storage.lifecoach/", "StorageService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://introsde-lifecoach-storage.herokuapp.com/ws/storage/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGESERVICE_WSDL_LOCATION = url;
        STORAGESERVICE_EXCEPTION = e;
    }

    public StorageService() {
        super(__getWsdlLocation(), STORAGESERVICE_QNAME);
    }

    public StorageService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGESERVICE_QNAME, features);
    }

    public StorageService(URL wsdlLocation) {
        super(wsdlLocation, STORAGESERVICE_QNAME);
    }

    public StorageService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGESERVICE_QNAME, features);
    }

    public StorageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGESERVICE_EXCEPTION != null) {
            throw STORAGESERVICE_EXCEPTION;
        }
        return STORAGESERVICE_WSDL_LOCATION;
    }

    /**
     *
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "StorageImplementationPort")
    public Storage getStorageImplementationPort() {
        return super.getPort(new QName("http://webservice.storage.lifecoach/", "StorageImplementationPort"), Storage.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Storage
     */
    @WebEndpoint(name = "StorageImplementationPort")
    public Storage getStorageImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.storage.lifecoach/", "StorageImplementationPort"), Storage.class, features);
    }

}
