
package ws.business;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "Business", targetNamespace = "http://webservice.business.lifecoach/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface Business {


    /**
     * @param person
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.CreatePersonResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/createPersonRequest", output = "http://webservice.business.lifecoach/Business/createPersonResponse")
    int createPerson(
            @WebParam(name = "person", targetNamespace = "http://webservice.business.lifecoach/")
                    Person person);

    /**
     * @param person
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "personId", targetNamespace = "")
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.UpdatePersonResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/updatePersonRequest", output = "http://webservice.business.lifecoach/Business/updatePersonResponse")
    int updatePerson(
            @WebParam(name = "person", targetNamespace = "http://webservice.business.lifecoach/")
                    Person person);

    /**
     * @param personId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeletePersonResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/deletePersonRequest", output = "http://webservice.business.lifecoach/Business/deletePersonResponse")
    int deletePerson(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId);

    /**
     * @param measure
     * @param personId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "measureId", targetNamespace = "")
    @RequestWrapper(localName = "createMeasure", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.CreateMeasure")
    @ResponseWrapper(localName = "createMeasureResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.CreateMeasureResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/createMeasureRequest", output = "http://webservice.business.lifecoach/Business/createMeasureResponse")
    int createMeasure(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId,
            @WebParam(name = "measure", targetNamespace = "http://webservice.business.lifecoach/")
                    Measure measure);

    /**
     * @param measure
     * @param personId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "measureId", targetNamespace = "")
    @RequestWrapper(localName = "updateMeasure", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.UpdateMeasure")
    @ResponseWrapper(localName = "updateMeasureResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.UpdateMeasureResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/updateMeasureRequest", output = "http://webservice.business.lifecoach/Business/updateMeasureResponse")
    int updateMeasure(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId,
            @WebParam(name = "measure", targetNamespace = "http://webservice.business.lifecoach/")
                    Measure measure);

    /**
     * @param measureId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteMeasure", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeleteMeasure")
    @ResponseWrapper(localName = "deleteMeasureResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeleteMeasureResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/deleteMeasureRequest", output = "http://webservice.business.lifecoach/Business/deleteMeasureResponse")
    int deleteMeasure(
            @WebParam(name = "measureId", targetNamespace = "")
                    int measureId);

    /**
     * @param personId
     * @return returns java.util.List<ws.business.GoalBusiness>
     */
    @WebMethod
    @WebResult(name = "listGoalBusiness", targetNamespace = "")
    @RequestWrapper(localName = "getGoals", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.GetGoals")
    @ResponseWrapper(localName = "getGoalsResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.GetGoalsResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/getGoalsRequest", output = "http://webservice.business.lifecoach/Business/getGoalsResponse")
    List<GoalBusiness> getGoals(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId);

    /**
     * @param goal
     * @param personId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "goalId", targetNamespace = "")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.CreateGoalResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/createGoalRequest", output = "http://webservice.business.lifecoach/Business/createGoalResponse")
    int createGoal(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId,
            @WebParam(name = "goal", targetNamespace = "http://webservice.business.lifecoach/")
                    Goal goal);

    /**
     * @param goal
     * @param oldTitle
     * @param personId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "goalId", targetNamespace = "")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.UpdateGoalResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/updateGoalRequest", output = "http://webservice.business.lifecoach/Business/updateGoalResponse")
    int updateGoal(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId,
            @WebParam(name = "goal", targetNamespace = "http://webservice.business.lifecoach/")
                    Goal goal,
            @WebParam(name = "oldTitle", targetNamespace = "")
                    String oldTitle);

    /**
     * @param goalId
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteGoal", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeleteGoal")
    @ResponseWrapper(localName = "deleteGoalResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeleteGoalResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/deleteGoalRequest", output = "http://webservice.business.lifecoach/Business/deleteGoalResponse")
    int deleteGoal(
            @WebParam(name = "goalId", targetNamespace = "")
                    int goalId);

    /**
     * @param goalId
     * @param title
     * @return returns int
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteGoalByTitle", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeleteGoalByTitle")
    @ResponseWrapper(localName = "deleteGoalByTitleResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.DeleteGoalByTitleResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/deleteGoalByTitleRequest", output = "http://webservice.business.lifecoach/Business/deleteGoalByTitleResponse")
    int deleteGoalByTitle(
            @WebParam(name = "goalId", targetNamespace = "")
                    int goalId,
            @WebParam(name = "title", targetNamespace = "")
                    String title);

    /**
     * @param personId
     * @return returns ws.business.Bmi
     */
    @WebMethod
    @WebResult(name = "bmi", targetNamespace = "")
    @RequestWrapper(localName = "getBmi", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.GetBmi")
    @ResponseWrapper(localName = "getBmiResponse", targetNamespace = "http://webservice.business.lifecoach/", className = "ws.business.GetBmiResponse")
    @Action(input = "http://webservice.business.lifecoach/Business/getBmiRequest", output = "http://webservice.business.lifecoach/Business/getBmiResponse")
    Bmi getBmi(
            @WebParam(name = "personId", targetNamespace = "")
                    int personId);

}
